version: '3.8'
services:
    db:
        container_name: books_postgres_container11
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: test_db
        ports:
            - '5432:5432'
        command: postgres -c listen_addresses='*'
    pgadmin:
        container_name: books_pgadmin11_container11
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - '5050:80'
    app:
        container_name: books_app_container11
        build: ./
        restart: always
        ports:
            - '3000:3000'
        depends_on:
            - db
